### ISSUE TITLE
'Application ID URI' - api://localhost:44355 can't be used.

### ISSUE THREAD

**Issue by tarunchopra** [OfficeDev/Office-Add-in-ASPNET-SSO#1]
I followed the instructions listed under 'Register the add-in with Azure AD v2.0 endpoint' section @ https://dev.office.com/docs/add-ins/develop/create-sso-office-add-ins-aspnet. While registering the app; if I enter 'Application ID URI' as 'api://localhost:44355' then I get following error. I've replaced the port to be 44350 for testing and hope it will work fine.
![capture](https://cloud.githubusercontent.com/assets/16295309/26090053/26953292-39b7-11e7-9fa2-ac99f792b03e.PNG)

**Comment by Rick-Kirkham** [comment]
That will work. You should also search the project in VS for "44355" and change every instance to "44350".
Also, close VS, and then outside of VS in a text editor, search the files for "44355" and change them. I believe there are 2 places in csproj files where that string appears.
