### ISSUE TITLE
question on SSO and user consent

### ISSUE THREAD

**Issue by LeanderVanEck** [OfficeDev/Office-Add-in-ASPNET-SSO#10]
We have the following scenario.

Before we used the V1 endpoint for authentication. We have now upgraded to use the V2 endpoint and included SSO. Of course this will use a converged app and our customers should consent again to the application.

However where do we trigger this consent question?

We have put all required scopes in the manifest. But as i understood this will only trigger consent request when adding the app from the store. This is only viable for new users and not our current userbase who already have the app installed.

When user is not logged in to office the following call will open a login dialog

`Office.context.auth.getAccessTokenAsync({ forceConsent: true },`

But again it doesn't ask for consent.

So what would be the suggested approach in this use case?

Also i'm not sure what the `forceConsent` parameter is supposed to do. I tried setting it to false, but it gives the exact same behavior on my end. Is this parameter only active on certain office versions?

**Comment by LeanderVanEck** [comment]
Noticed that `forceConsent` doesn't do anything when my addin is running from localhost. But after installing the addin from the store we do notice that `forceConsent` will trigger a consent dialog.

However after the consent dialog is confirmed the getAccessTokenAsync method always returns with a 13007 error and co consent for the app is granted.

I've tried the following:

1. trigger SSO with forceConsent: false
2. Error 13007 is returned
3 trigger SSO with forceConsent: true
4. Consent dialog is shown, click continue
5. Error 13007 is returned, there is still no consent for the app.

The manifest includes the following scopes

```
<Scopes>
        <Scope>openid</Scope>
        <Scope>offline_access</Scope>
        <Scope>files.readwrite.all</Scope>
        <Scope>sites.readwrite.all</Scope>
        <Scope>user.read</Scope>
        <Scope>user.readbasic.all</Scope>
        <Scope>contacts.read</Scope>
        <Scope>people.read</Scope>
        <Scope>mail.send</Scope>
        <Scope>email</Scope>
</Scopes> 
```
After manually consenting the app (login.microsoftonline.com/authorize) SSO starts working as expected.

So eventually we might be able to work around this problem by automating a consent dialog through code. But of course it would preferable to have this work with SSO.

Additional questions relating to this.

- Is there any documentation available on what parameters can be used for getAccessTokenAsync and what they are supposed to do?
- Is there any documentation available on the error codes that can be returned from getAccessTokenAsync?

It would be appreciated if there is some information on how to configure everything for a real user scenario. I've found a walkthrough from a developer perspective and in one of the steps it mentions to give admin consent, but this doesn't explain how to handle user consent in a user scenario.

I have installed latest version of Office 1708 semi-annual.

Any help would be most welcome.

**Comment by Rick-Kirkham** [comment]
@LeanderVanEck 
We are looking into your problem with forceConsent.

We discovered recently that to avoid 13007, it is necessary to ask for "profile" permission in the Microsoft Graph Permissions section of the registration. You should then repeat the admin consent process. This should get it working in development. You should also add a <Scope>profile</Scope> to the manifest so it will work when a user installs it from the store. 

We are just a week or so away from updating our SSO documentation and making more of it public. This will include error code docs. I can tell you that 13007 means that the Office host application was unable to get an access token to your add-in's web application. 

Also, here are the possible properties for the options parameter to getAcessTokenAsync:
Property | Type | Description
-- | -- | --
forceConsent | bool | Optional. Causes Office to display the add-in consent experience. Useful if the add-in's Azure permissions have changed or if the user's consent has been revoked.
forceAddAccount | bool | Optional. Prompts the user to add (or to switch if already added) his or her Office account.
asyncContext | any | Optional. A user-defined item of any type that is returned in the AsyncResult object without being altered.
authChallenge | string | Optional. Use this in a second call of getAccessTokenAsync, when a first call returns an error from Microsoft Graph indicating that the user must provide a 2nd form of identification. The error will include the string that should be passed as the value of authChallenge.

**Comment by LeanderVanEck** [comment]
@Rick-Kirkham 

Thanks for your response. We will try publishing to the store again with the profile scope included in the manifest. I will let you know what our results are after the app gets approved.

It is also good to read about the other parameters for getAccessTokenAsync. The authChallenge might be important for some of our customers. (When SSO fails we still fall back to a manual login, but of course SSO gives a better user experience)

**Comment by TimMcMSFT** [comment]
Hi Leander, everything that you're describing sounds in-line with our expectations. We're working through the developer experience to remove the inconsistencies. I want to get to your question: "where do we trigger this consent"? The answer is that, aside from side-loaded add-ins, Office will handle the Consent experience for you. Either at acquisition time for users or at submission time for admins with corporate catalog. This Consent experience is critical, and it must happen before Office can properly acquire Tokens. There are cases where forceConsent is appropriate: 1) If Office fails to get a Token and returns a 13005. 2) If you are exchanging the initial Token from Office for a Graph Token in your service, it's possible that the permissions or Consent have changed, and the Graph request fails. In both of these cases, the add-in uses the forceConsent option to prompt the user for her permissions. Office UI should be used to handle all Graph permissions.

**Comment by LeanderVanEck** [comment]
@TimMcMSFT 

The developer walkthrough is pretty straightforward. But in a production scenario we are slightly struggling with configurations and how to handle consent and exceptions in an appropiate way.
But we're working through it and the help you guys are providing has been awesome.

With the `profile` scope included in the manifest i think the `forceConsent` parameter is now working as it should. At least i noticed app permission being added on my office 365 account. I'll try to do some more testing to make sure. Retracting the permissions seems to need some time before it takes effect, so it is not easy to test this.

When everything works, the consent experience is very nice. I actually think the whole thing looks amazing.
