### ISSUE TITLE
getAccessTokenAsync returns error 13003

### ISSUE THREAD

**Issue by AlexUrbanAc** [OfficeDev/Office-Add-in-ASPNET-SSO#13]
In Outlook 16.0.8431, I get the following result when calling 

Office.context.auth.getAccessTokenAsync(function(token) {console.log(token)});

error:{
code: 13003,
message: "Der Identitätstyp des Benutzers wird nicht unterstützt.",
name: "Der Benutzeridentitätstyp wird nicht unterstützt."
},
status:"failed",
value: undefined

The user who's profile I have loaded in Outlook, however, is the admin of our O365 tenant, not a guest or something like that. (and is different from the on-premise account I have used for windows login). My guess is this is caused by our tenancy, which may be a bit messed up because hybrid configuration.

Getting the callback token works, by the way, and when I decode the callback token, the payload tells me who is logged in:

{
  "nameid": "0026eab0-afba-43fe-a3fa-c479b6feecca@09265c06-fa36-4a7a-90cd-e3c2b0dd1c39",
  "ver": "Exchange.Callback.V1",
  "appctxsender": "https://.../index.html@09265c06-fa36-4a7a-90cd-e3c2b0dd1c39",
  "appctx": "{\"oid\":\"d11a77b0-5b5a-45b8-8d24-3d7ba4b386b9\",\"puid\":\"10037FFE8F3B6DD9\",\"smtp\":\"someuser@ourtenant.onmicrosoft.com\",\"upn\":\"someuser@ourtenant.onmicrosoft.com\",\"scope\":\"ParentItemId:\"}",
  "iss": "00000002-0000-0ff1-ce00-000000000000@09265c06-fa36-4a7a-90cd-e3c2b0dd1c39",
  "aud": "00000002-0000-0ff1-ce00-000000000000/outlook.office365.com@09265c06-fa36-4a7a-90cd-e3c2b0dd1c39",
  "exp": 1508832771,
  "nbf": 1508832471
}

However, the User Identity token, when decoded, doesn't:

{
  "appctxsender": "00000002-0000-0ff1-ce00-000000000000@09265c06-fa36-4a7a-90cd-e3c2b0dd1c39",
  "isbrowserhostedapp": "True",
  "appctx": "{\"msexchuid\":\"b79dfdc0-a9a6-49f1-bffe-1497a3be7ee1\",\"version\":\"ExIdTok.V1\",\"amurl\":\"https://outlook.office365.com:443/autodiscover/metadata/json/1\"}",
  "iss": "00000002-0000-0ff1-ce00-000000000000@09265c06-fa36-4a7a-90cd-e3c2b0dd1c39",
  "aud": "https://.../index.html",
  "exp": 1508861192,
  "nbf": 1508832392
}

What is wrong and how can I fix this?

**Comment by Rick-Kirkham** [comment]
It may be that the user is logged in with more than one account. Another possibility is that Office has kept an identity in the cache even though it appears that you've changed identities. Try this: log off from all identities in Office and close all Office applications, not just Outlook. Then try again. 

Question: You say that "Getting the callback token works". Do you mean that  you get 13003 error AND you get the token, in the same call of **getAccessTokenAsync**?

**Comment by AlexUrbanAc** [comment]
The callback token is returned by Office.context.mailbox.getCallbackTokenAsync, the user identity token by Office.context.mailbox.getUserIdentityTokenAsync.
