### ISSUE TITLE
Microsoft.Identity.Client will not install, and no newer version is available

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/Office-Add-in-ASPNET-SSO#14]
I get this error when trying to restore the nuget packages

![image](https://user-images.githubusercontent.com/9402456/32193275-827e86ba-be02-11e7-8d6c-50b1da7c6603.png)

I'm using visual studio 2017  v15.3.4

I tried searching for a another version of Microsoft.Identity.Client and found Microsoft.Identity.Client.1.1.0-preview so I installed this.

But now I get this issue

![image](https://user-images.githubusercontent.com/9402456/32193508-3ab307b0-be03-11e7-9b6a-68dc65cb3ab7.png)

So then I go and downgrade to different versions, which are available, but just get different errors.

So now the code is way out of wack with any available identity.client nuget packages, making it impossible to run, unless of course, when knows how to write code against the latest client ("which I don't, which is why I'm learning from this sample")

Can you guys please update this repo?

Cheers

**Comment by Rick-Kirkham** [comment]
@nigel-dewar 
Please see the **Important** note in the Prerequisites section and follow the instructions there.

**Comment by nigel-dewar** [comment]
Thank you @Rick-Kirkham , my bad.

**Comment by loflet** [comment]
I am facing the same issue. Checked the Prerequisites section and the command that is mentioned there is referring to this as Source https://www.myget.org/F/aad-clients-nightly/api/v3/index.json but the package is not present there.
![image](https://user-images.githubusercontent.com/7891707/43136409-41c1b1de-8f66-11e8-873b-61e819f8d7e5.png)

**Comment by Rick-Kirkham** [comment]
Please try this command `Install-Package Microsoft.Identity.Client -Version 1.1.4-preview0002`

And please report back here whether it works or not. Thanks.

**Comment by loflet** [comment]
Hello @Rick-Kirkham , thank you for the updated package. The package is installed successfully. I will let you know if there is any issue with this reference. You can close this issue.
