### ISSUE TITLE
The identity API is not supported for this add-in.

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/Office-Add-in-ASPNET-SSO#15]
Thank you provider this sample to implement SSO within office add-in. This is really complex.

To simplify and clean, I start with this code in a normal office add-in, 
```
    function ssologin() {
        Office.context.auth.getAccessTokenAsync(function (result) {
            if (result.status === "succeeded") {
                // No need to prompt user, use this token to call Web API
                var ssoToken = result.value;
                showNotification(ssoToken);
            } else {

                showNotification(result.error.message);
            }
        });
    }

```

but I got the error as below, what's the problem? thank you 

`The identity API is not supported for this add-in.`

**Comment by Rick-Kirkham** [comment]
You need to make changes to the manifest as well as add that code to the normal Office add-in. Also, you need to have a version of Office that supports SSO. Please see this article for how to create an SSO add-in: 
[Create SSO Office Add-in using ASP.NET](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet)

**Comment by PieterVm** [comment]
Doesn't work for me either
