### ISSUE TITLE
.auth is undefined

### ISSUE THREAD

**Issue by PieterVm** [OfficeDev/Office-Add-in-ASPNET-SSO#16]
Office.context.auth doesn't work for me. The 'auth' part is undefined and I have no idea why.

**Comment by Rick-Kirkham** [comment]
I sounds like you have a version of Office that doesn't support SSO.  Please see the Prerequisites of the Readme of this repo for the required version and build.

**Comment by PieterVm** [comment]
You're right, didn't see that. But now the next problem occurs.. In the same code block 'result' = failed.
Error 13007 (saw the blogpost about this issue but nothing worked, had 'profile' en all the other thing done)

**Comment by Rick-Kirkham** [comment]
If you haven't already, please take a look at [Troubleshooting SSO](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins).

If you're still having trouble, please provide the AAD registration manifest. You can replace URLs and other identifying info with fake data. Thanks.

**Comment by Rick-Kirkham** [comment]
Closing because haven't heard from customer.
