### ISSUE TITLE
code : 5001 message : "An internal error has occurred." name : "Internal Error" When calling getAccessTokenAsync

### ISSUE THREAD

**Issue by jagathWijesinghe** [OfficeDev/Office-Add-in-ASPNET-SSO#17]
code:5001
message:"An internal error has occurred."
name:"Internal Error"
I get this when I call getAccessTokenAsync method. I also tried with AttachementDemo sample it also gives the same error. In desktop version I get error:13003

**Comment by Rick-Kirkham** [comment]
Please see if the error message information in this topic can help: [Troubleshoot SSO in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins).
Also, sometimes an identity doesn't get cleared from the Office cache, so you are logged in under two identities even though it looks like you are logged in under only one. Try this: Logout completely from Office. Close all Office applications. Login again.
