### ISSUE TITLE
The host name should not be based on already owned domain

### ISSUE THREAD

**Issue by guyhleejr** [OfficeDev/Office-Add-in-ASPNET-SSO#19]
I went through the [document ](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet) which supports this project.  When I registered the Add-in with Azure AD v2.0, (Web API) with "localhost:44355" as the Web API "Application ID URI" I could get it to work; however, once I moved the website to Azure and then updated the URI to the new website I receive the following error:

"Your changes could not be saved"
"The host name should not be based on already owned domain."

Are you aware of this error?

**Comment by Rick-Kirkham** [comment]
@guyhleejr We believe that error is caused when the web application is configured as multi-tenant. SSO does not yet support multi-tenant add-ins. See this issue: https://github.com/OfficeDev/office-js-docs-pr/issues/40

**Comment by guyhleejr** [comment]
Thanks for the response Rick; however, I don't see how to change it from multi-tenant if this is the issue.  I've scoured the app service's properties and don't see an option to change it.  Do you have a link you can refer me to on how to make this change?

Also, I created a different website (not in Azure) to host the server code and get the same error.  Could there be something else that is causing this error?

**Comment by Rick-Kirkham** [comment]
@guyhleejr 
It looks like this setting is not surfaced in the UI on https://apps.dev.microsoft.com.
Go to the registration page for your add-in's web application.
Scroll down to the botton and click the button to edit the manifest.
Near the bottom of the manifest there is a "tags" property. One subproperty is "availableToOtherTenants". I think (but I'm not sure) that this is the relevant setting. It looks like it defaults to "true", which does no harm when you are working on localhost; but causes the error about "already owned domain" on any other domain.
Please try setting this value to "false" and then save the manifest.
See if that fixes the issue.
PLEASE REPORT BACK HERE THE OUTCOME. If it works, I will add this to the documentation.

**Comment by guyhleejr** [comment]
Thank you for your expedient help @Rick-Kirkham,

I think you may be on to something here.  That is, I don't have an additional registration other than the one in https://apps.dev.microsoft.com.  Here are my overall steps (using the Sample):

1. created an app service in Azure and published the "Office-Add-in-ASPNET-SSO-WebAPI" to it
2. used the URL for the Web site and the Web API Platforms in "https://apps.dev.microsoft.com" and received an error.  

NOTE: it will save if I remove the Web API Platform

If I open Azure Portal and scroll down to "Azure Active Directory" and then click "App registrations" my App doesn't display.  I have to select the link labeled "Microsoft Application Console" to adjust its settings.

3. I then created an (additional) App registration (in Azure Active Directory) using the same URL as the app service.  I open the settings and then view the Manifest and validate that "availableToOtherTenants" is set to "false".

4.  I launched https://apps.dev.microsoft.com and added the Web API Platform and changed the Application ID URI to "api://<app service url>/<application id>" and received the same error.

Is there anything glaring in the process?  Should I have two App registrations?

Thanks,

Guy

**Comment by Rick-Kirkham** [comment]
@guyhleejr 
I don't think you need two registrations. I can't quite follow your description, but you mention working in the Azure Portal. I do ONLY what's described in  [document](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet). I never do anything in the Azure portal. Could I ask you to delete the registration in "https://apps.dev.microsoft.com", and then create a new one _exactly_ as described in the [document](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet), plus the additional step of setting "availableToOtherTenants" to "false"?

**Comment by guyhleejr** [comment]
I'm sorry about that @Rick-Kirkham.  I must have had my wires crossed.

I did what you asked and created the registration (and left the Web API Platform as "localhost").  I saved the registration and then opened the Manifest and found the entry "availableToOtherTenants" and set it to "false".  I then went back in to the same registration and changed the Web API Platform to the URL (<something>.azurewebsites.net) and still received the error message.

![image](https://user-images.githubusercontent.com/20933844/36916766-daaa2486-1e22-11e8-8004-f2d198c590bc.png)

**Comment by Rick-Kirkham** [comment]
I'll see if I can get some help from the product team.

**Comment by Rick-Kirkham** [comment]
This is what I learned from the product team: AzureWebsites.net addresses cannot be used in Azure AD today, since you cannot prove ownership. You will need to host your add-in on a different domain.

**Comment by guyhleejr** [comment]
Thanks for the information @Rick-Kirkham.  Your explanation from the product team makes sense; however, with a hosted domain (not Azure) I still get the same error.  


![image](https://user-images.githubusercontent.com/20933844/37097785-50c0b598-21ea-11e8-87b1-29ce6694e698.png)

**Comment by TimMcMSFT** [comment]
Hi @guyhleejr, is it possible that you or someone else in your organization has registered your .org Domain with an Azure subscription?

**Comment by guyhleejr** [comment]
Hello @TimMcMSFT,

Sorry, I'm not exactly sure how to check.  I set the .org site (godaddy) up with my personal information to make sure it was completely separate.  Is there something I can verify?  For your information, I've been attempting to set up SSO using my MSDN Azure subscription.  I use an "*.msn.com" account to access the Azure Portal (where I initially had the web app setup).  I use a "*.onmicrosoft.com" address to access the Office 365 admin portal (where I have the add-in registered).  

Note: I can register the add-in if I point the api URI to a non-existent subdomain (on my .org site).

**Comment by guyhleejr** [comment]
Is there any update on this issue?  Maybe a work-around?

**Comment by TimMcMSFT** [comment]
Yes, @guyhleejr, if you own this domain, then you can set it up with this process: https://docs.microsoft.com/en-us/azure/active-directory/add-custom-domain

Once you've completed those steps, you'll be able to use that Resource Url for your Azure apps.

**Comment by guyhleejr** [comment]
Thank you so much @TimMcMSFT.  Once I added the custom domain, I'm now able to get past the error.  My end-to-end test has succeeded!

**Comment by TimMcMSFT** [comment]
Glad to hear it!
