### ISSUE TITLE
getAccessTokenAsync returns error 7000 Permission Denied

### ISSUE THREAD

**Issue by tnsholding** [OfficeDev/Office-Add-in-ASPNET-SSO#2]
I'm trying to run the sample Office-Add-in-ASPNET-SSO. 
The add-in displays fine in PowerPoint, but clicking the button 'Get My Files from OneDrive' causes the call to Office.context.auth.getAccessTokenAsync to return an error: code=7000, Name='Permission Denied', message:'You don't have sufficient permissions for this action'.

I'm pretty sure, that I have followed the instructions and registered the Azure AD v2.0 endpoint correctly. 

So what could cause the call to getAccessTokenAsync to fail with permission denied?

NB: Using ngrok service to tunnel request to localhost. So all code refs to localhost:44355 changed to (id).ngrok.io (including web and web api urls in apps.dev.microsoft.com registration).

**Comment by tarunchopra** [comment]
Can you attach fiddler trace? Which version of msal are you using ?

**Comment by Rick-Kirkham** [comment]
Also, of course, please try the sample exactly as in the instructions (no ngrok!) to see if it works. That will help us tell isolate if the error is connected with the use of ngrok.

**Comment by tnsholding** [comment]
The instructions didn't work with localhost:44355. Error in registering api endpoint: "Your Application ID URI must be globally unique.".
I have now changed all urls to localhost:44395, so everything should now be exactly as in the instructions except the changed port number. But still getting the same error. 

I noticed that my Office 2016 version is 1610 (build 7466.2038). Could that cause the issue?
My organisation has disabled installing Office 2016 through the portal (think Office is rolled out with SCCM), and when checking for updates, Office tells me that I already have the latest version...

**Comment by tnsholding** [comment]
Managed to obtain a newer version of Office 2016 - now running 1704 (build 8067.2115). 
Can confirm that the error returned from getAccessTokenAsync was related to the version of Office. Everything is working now.

**Comment by Rick-Kirkham** [comment]
@tnsholding 
You are the second person to get that "globally unique" error. I'm researching this and will change the instructions as needed. Thanks.

Update: We have changed our guidance to fix the "globally unique" error. The GitHub version of the new instructions are here: https://github.com/OfficeDev/office-js-docs/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md
The dev.office.com version should be updated in a few days. 
The change is simple. We now add the application GUID to the **Application ID URI** when registering the add-in. We change the WebApplicationResource value in the add-in manifest to match the new ID URI
