### ISSUE TITLE
Error while build application

### ISSUE THREAD

**Issue by gomteshhatgine** [OfficeDev/Office-Add-in-ASPNET-SSO#20]
I was getting this error while build project

The element 'VersionOverrides' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' has invalid child element 'WebApplicationInfo' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'. List of possible elements expected: any element in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides/1.1'.

**Comment by Rick-Kirkham** [comment]
This error normally means that your version of Office does  not support SSO. What is your version of Office?

**Comment by guyhleejr** [comment]
If you go through the [associated document](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet), you should see a section that may cover this issue:

![image](https://user-images.githubusercontent.com/20933844/37355923-3e6eda7a-26bb-11e8-81fc-43161ec11bc8.png)
