### ISSUE TITLE
The type 'SecurityToken' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IdentityModel, Version=4.0.0.0

### ISSUE THREAD

**Issue by gomteshhatgine** [OfficeDev/Office-Add-in-ASPNET-SSO#21]
When I add OpenIdConnectCachingSecurityTokenProvider and Startup.Auth files in my BotBuilder project, Also I added respective references as required but when I try to build I was getting an error:
 The type 'SecurityToken' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IdentityModel, Version=4.0.0.0

Even I added System.IdentityModel.Tokens.Jwt v:4.0.0 
and I was Microsoft.Bot.Builder 3.5.9.0

**Comment by Rick-Kirkham** [comment]
Is this a problem with the sample or with your own add-in? If the latter, please ask this question on Stackoverflow and tag it "office-js", "owin". 

FWIW, the sample has both System.IdentityModel  and System.IdentityModel.Tokens.Jwt listed in the References in Solution Explorer.

**Comment by gomteshhatgine** [comment]
Thanks its working 
Yes I have forgot to add  System.IdentityModel seperately, Now thats work for me

But I have one more query,

As in sample, defined OpenIdConnectCachingSecurityTokenProvider,Startup.Auth in API project
But is this possible to define those changes in separate MVC api project instead on same addin project solution 

1. - Even I have added those files in AppStart, Startup.cs and values controller in same add-in project then also its not working.
IS something I missing??


2. - In add-in when I call ajax call url "/api/values" then its returning 404 i.e resource not found because add-in is running on https://localhost:44355 and WebAPI on http://localhost:33172/ 
. because domain of add-in and webAPI project is diffrent in every add-in project while running add-in project its run two application shown in IIS Express. So in your project how "api/values" will call webAPI controller of http://localhost:33172/  as that add-in is running in another domain i.e https://localhost:44355 
So How WebAPI and Add-in domain must be same As they are running on different urls such ashttp://localhost:33172/  and   https://localhost:44355  respectively?? SO how could be same??
 
3. One more thing I observed that when I run your add-in project while loading project call comes into OpenIdConnectCachingSecurityTokenProvider method How add-in will know to call this method of API project?? In my case it is not calling that method
Even I was getting token for method  Office.context.auth.getAccessTokenAsync method from where its acually getting token?

**Comment by gomteshhatgine** [comment]
Even I have added those files in same add-in project then also its not working.
Also when its call url "/api/values" so its returning 404 i.e resource not found

**Comment by Rick-Kirkham** [comment]
@gomteshhatgine Your description indicates that you are not working with the sample. You are developing a separate add-in. Please raise your question on StackOverflow and tag it "office-js", "owin".
Also, please note from this article that the add-in and the web API must have the same fully qualified domain name: [Enable SSO for Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
