### ISSUE TITLE
Add-In failing with error 13007 "Error occurred in the authentication provider."

### ISSUE THREAD

**Issue by govanikunal** [OfficeDev/Office-Add-in-ASPNET-SSO#23]
On click of "Get My Files from OneDrive", it fails with error 13007 "Error occurred in the authentication provider."

![image](https://user-images.githubusercontent.com/19185363/38975063-01e21636-43ca-11e8-8fe9-571093c8ae31.png)

i tried to follow below issue, but doesn't see any solution at end of it. The permission mentioned there are already given for my registered application.

[https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/issues/2](https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/issues/2)

Looking for some insights on this, 

Thanks,
Kunal

**Comment by Rick-Kirkham** [comment]
Have you checked the Troubleshooting article for 13007? [Troubleshoot SSO in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins)

**Comment by govanikunal** [comment]
Hi Rick,

Yes, i have tried that. Also gone through the close issues under this stream & tried those suggestions. Still no luck

When i run the app & open from Powerpoint Task pane, If i am running for first time with a user, shouldn't it ask for the user consent ?. 

I am not seeing that, which i believe might be the reason for the issue.

**Comment by Rick-Kirkham** [comment]
If you've already provided Admin consent, then the user won't get a consent prompt. I'll ask someone from  the product team to help.

**Comment by TimMcMSFT** [comment]
Consent is only provided 1) at acquisition time or 2) on demand by the add-in. Our sample does not support #2.

@govanikunal, can you confirm that you made Admin consent for the Tenant and that you're testing with a user from that same Tenant? 

If so, then we probably need to see the Add-in and Azure app manifests from your project.

**Comment by govanikunal** [comment]
@TimMcMSFT Yes, Admin consent was done & Accept was clicked. 

I am trying to run with my user, both are under same Tenant

**Comment by tabi786** [comment]
Hi,

Any status with this error? I have tried to run it both on localhost and also by publishing it on Azure with custom domain and SSL. It doesn't work. By publishing on Azure it shows the "AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '57fb890c-0dab-4253-a5e0-7188c88b2bb4'." I have attached error screenshot of the error, web.config, addin manifest and app manifest (For security reason I have removed the password from web.config and app manifest). 

[XoCareEmailManager.zip](https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO/files/1948435/XoCareEmailManager.zip)

Your quick response in this regard will be highly appreciated.

Regards.

**Comment by Rick-Kirkham** [comment]
@tabi786 Did you get a different error when you tried localhost? If so, what was it?

One thing I notice in your files is that you are asking for 10 scopes in the app manifest, but only 4 in the add-in manifest. I don't know if that is causing your problem, but I believe that those two lists of scopes should match. Please add the additional 6 scopes to the add-in manifest and try again on localhost. 

Also, 57fb890c-0dab-4253-a5e0-7188c88b2bb4 is the ID of Office Online, so I assume you are testing with Office Online. Can you test with desktop Office (the subscription, "click-to-run" version)? It might be informative if you don't get 50011 with desktop.

Edit: One more thing I noticed. For "publisherDomain" in my app manifest, I have the domain of my Office 365 tenancy: something.onmicrosoft.com. I notice that your publisherDomain is xo-care.com. Is that the domain of your Office 365 tenant?

**Comment by TimMcMSFT** [comment]
@tabi786 -- What's the Full Url that's in the browser when you get the error (shown in the screenshot)?

The screenshot is of a pure Browser environment, but the error message suggests that this is failing in Office Online.

In your test environment, are you using a guest account? Does your environment have a vanity/custom domain? Have you gone through the consent experience for a user/admin?

**Comment by tabi786** [comment]
@TimMcMSFT  This is Full Url that I get back.

https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id=57fb890c-0dab-4253-a5e0-7188c88b2bb4&resource=api://api.xo-care.com/eaf6af03-ae8b-433b-be6d-4924571b9b06&redirect_uri=https://xocare.sharepoint.com/_forms/singlesignon.aspx&state=9ec43fdb-9326-4046-a71c-4d4c39a779e7|api://api.xo-care.com/eaf6af03-ae8b-433b-be6d-4924571b9b06&client-request-id=0f4031a0-c409-4945-a2f3-b668b86c6cdf&x-client-SKU=Js&x-client-Ver=1.0.16&prompt=none&login_hint=jec@xo-care.com&domain_hint=xo-care.com&iframe-request-id=5ec478a6-99c1-41c8-9bfe-2961bcbf1700

**Comment by tabi786** [comment]
@TimMcMSFT I have tried it in PowerPoint online. I am testing it with my Global Admin account and it is not a test account. Our domain is domain of our Office 365 tenant. Yes, I have also gone through Grant administrator consent to the add-in via this Url https://login.microsoftonline.com/common/adminconsent?client_id=eaf6af03-ae8b-433b-be6d-4924571b9b06&state=12345

Thank you in advanced 😃

**Comment by tabi786** [comment]
@Rick-Kirkham I have also tried only with 4 scopes and it has the same error. yes xo-care.com is domain of our Office 365 tenant. I can't modify it, it is read only in the manifest. If I try to set api://apixocare.azurewebsites.net/eaf6af03-ae8b-433b-be6d-4924571b9b06 in App Manifest then I get error "The host name should not be based on already owned domain". Therefore I have configured my custom domain and a valid SSL on Azure Web App.

I have also tried it in PowerPoint desktop. It isn't throwing any error it but it doesn't either fetching one drive files.

**Comment by TimMcMSFT** [comment]
Thanks, @tabi786. I think I know what's happening here. Since no users have acquired / consented to your application in the Tenant, then the application hasn't been fully configured. That's why you see issues in PowerPoint Online but not in PowerPoint Desktop (they are technically different applications). For the Online Case, please [sideload](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins) your add-in and consent through that experience. That will ensure that your add-in has been fully configured for the Tenant. For the PowerPoint Desktop flow, could you provide more details--for example, is Office returning a Token from the getAccessTokenAsync call? Would you share that Token or the error that you're hitting?

**Comment by tabi786** [comment]
@TimMcMSFT ok. I will try it and will back to you. Thank you so much.

**Comment by tabi786** [comment]
@TimMcMSFT It is working now for me after I have side loaded it. I have published it using Centralized Deployment via the Office 365 admin center. It is working fine now. Thank you so much 👍 

I need one last help if you can help. Have you any example that I can use to fetch data from a SharePoint List in this Office add-in using this token (Preferably using jquery/javascript)?
