### ISSUE TITLE
Reload Office content Add-In from powerpoint

### ISSUE THREAD

**Issue by govanikunal** [OfficeDev/Office-Add-in-ASPNET-SSO#24]
I have office web add-in added in my PowerPoint slides (multiple instances of add-in).  Need some settings that will be common across all add-in instances. for that tried to use VSTO Add-In and save those in settings file of it.

Now the issue is how i can pass those settings to each content add-in instances so i can read those in each add-in instance. 
OR
Is there a way where i can get handle of content add-in's context menu buttons 'Reload', so after any change from VSTO Add-In, can i just call 'Reload'. I can move settings in DB if needed.

![reloadimg](https://user-images.githubusercontent.com/19185363/40100317-2ebe6dac-5901-11e8-848a-4e7eb2209d26.png)

Appreciate any insights on this.

Thanks,
Kunal

**Comment by Rick-Kirkham** [comment]
@govanikunal Thanks for your interest in Office Add-ins. The Issues for this repo are intended only for problems with the sample. For technical questions about Office Add-ins, please ask a question on StackOverflow and tag it "office-js". It will be seen sooner and the whole community will benefit from the answers you get.

**Comment by govanikunal** [comment]
Thanks @Rick-Kirkham for the same. Posted it on stackoverflow as below:

https://stackoverflow.com/questions/50384059/reload-office-content-add-in-from-powerpoint-24
