### ISSUE TITLE
Get & Cache ONLY User Access Token in Addin

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/Office-Add-in-ASPNET-SSO#26]
Hi,
How to create flow only upto get and cache access token for O365 addin?
Please suggest me required NuGet Packeges with sample addin (if any).

**Comment by Rick-Kirkham** [comment]
@cognologixguru The Issues for this repo should be for bugs in the sample in this repo, not for general questions about SSO. Please raise your question on StackOverflow and tag it "office-js". That way more experts will see it, and the whole community will benefit from the answers that you get.
