### ISSUE TITLE
validation fails for manifest

### ISSUE THREAD

**Issue by dgrudenic** [OfficeDev/Office-Add-in-ASPNET-SSO#27]
if you try to do validation via validate-office-addin npm package you'll get error like:

Validation: Failed

Error #1:
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. (link: https://aka.ms/add-in-manifest-schema-violation)
  - Details: The element 'WebApplicationInfo' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' has incomplete content. List of possible elements expected: 'Authorizations' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'.
  - Line: 143
  - Column: 7

**Comment by Rick-Kirkham** [comment]
Strange. I've never heard of the `<Authorizations>` element. I'll investigate.

**Comment by Rick-Kirkham** [comment]
@dgrudenic This is a known bug that is being worked on. In the meantime, I don't think it will prevent the add-in from working.

**Comment by dgrudenic** [comment]
Sounds good. Thanks for quick reply.
