### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mingweiw** [OfficeDev/Office-Add-in-ASPNET-SSO#3]
When I tried to build the Complete solution I get a couple of errors. The first is about can't find the Microsoft.Identity.Client 1.1.0-alpha nuget package. I fixed that by updating to 1.1.0-preview. The second error is below. I'm not sure how to fix it. Can you help?

The element 'VersionOverrides' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' has invalid child element 'WebApplicationId' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'. List of possible elements expected: any element in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides/1.1'.

My Office version is 1707 (Build 8319.1000 Click-to-Run). I'm running VS 2017 version 15.2 (26430.14).

Let me know if you need more info.

Thanks!

**Comment by Rick-Kirkham** [comment]
Do you see this error when you press F5? If not, when do you see it?

**Comment by Rick-Kirkham** [comment]
You don't have the right version of VS. See the Prerequisites in the ReadMe. You need to have: Visual Studio 2017, version 15.3 (26424.2-Preview) or later.

**Comment by mingweiw** [comment]
I thought the 15.3 was a typo. According to [this](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes) 15.2 (26430.14) is the current version of VS (which I have). I don't see 15.3. Is 15.3 a typo? Do you know where I can get 15.3?

And yes, I see the error when I press F5.

Thanks.

**Comment by tarunchopra** [comment]
@mingweiw : Please upgrade to preview version : https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes
