### ISSUE TITLE
Issues deploying to Azure with 13004 error

### ISSUE THREAD

**Issue by bes3020** [OfficeDev/Office-Add-in-ASPNET-SSO#33]
Would it be possible to post a sample with values for the Manifest based on a completed version that has been published and updated in Azure.  I am having trouble understanding what values should be in the Manifest Resource and the App ID URI for the Azure app regisration.  I have this all working off the local server https://localhost:44355, but I get 13004 error Invalid application resource Url provided when calling Office.context.auth.getAccessTokenAsync.  

Also, does the App registration need to be in the same tenant as the website is being hosted?  My website is currently being hosted in <website>.azurewebsites.net.  Does this need to be matched up with the manifest resource and the App id URI?

**Comment by Rick-Kirkham** [comment]
You can actually make your own example. You should just replace the string `localhost:44355` everywhere that it appears in the manifest with the published domain, such as `addins.contoso.com` . But you have to _**REregister the app in AAD**_ using the new domain. The original localhost:44355 registration will no longer work after you've published the app to addins.contoso.com. 

There is a possible complication, however. The domain that you use in the **Expose an API** page of the Azure portal (which is the same domain that you use in the Resource of the manifest), has to be a domain that you own. At one time, and this may still be true, AAD did not consider you to be the owner of a subdomain of azurewebsites.net. If that's still true, then you have to give it an alternate domain name and use the alternate to REregister. See [Add your custom domain name using the Azure Active Directory portal](https://docs.microsoft.com/en-us/azure/active-directory/add-custom-domain).

**Comment by bes3020** [comment]
Thanks! I thought I might need an owned domain name. Going to try that and report back.

**Comment by bes3020** [comment]
This worked. Registered a domain and changed the manifest and app ID uri to base off the domain name. Thank you very much!
