### ISSUE TITLE
Can't Grant Consent

### ISSUE THREAD

**Issue by redcirkle** [OfficeDev/Office-Add-in-ASPNET-SSO#36]
[I've been following this guide](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet#grant-administrator-consent-to-the-add-in) to Create the SSO Office Add-ins ASP.NET project, but I'm unable to complete the "Grant administrator consent to the add-in" step. I've registered the app in the Azure portal with the necessary permissions, but the button to "Grant admin consent" is greyed out. 
![image](https://user-images.githubusercontent.com/19576266/67229438-29c52f80-f3f0-11e9-9fa5-df29750539b9.png)
![image](https://user-images.githubusercontent.com/19576266/67229455-2f227a00-f3f0-11e9-9c3e-16c9fb9af986.png)

When I run the application and the click the "Get My Files from OneDrive" button, I (rightly) get the AADSTS65001 error in the ValuesController.Get() method because there was a "call to AAD (which) contained at least one scope (permission) for which neither the user nor a tenant administrator has consented."
![image](https://user-images.githubusercontent.com/19576266/67229689-ace68580-f3f0-11e9-949c-3245fa8c5303.png)

How can I resolve this issue?

**Comment by Rick-Kirkham** [comment]
The only thing I can think of that would cause that would cause that button to be greyed out is that you are not logged in as an admin of the Office 365 tenancy. See step 2 of the article that you linked.

**Comment by redcirkle** [comment]
We created our app registration under the Microsoft tenant, but I am not an admin for that Office 365 tenancy. Is there a way to do single sign-on without being an admin for the tenancy?

**Comment by Rick-Kirkham** [comment]
If you can't give admin consent, then each user has to consent. Skip the step to grant admin consent. When your code gets the 65001 error, it should recall the getAccessTokenAsync method and pass the option `{ forceConsent: true }`. This will cause the user to get a consent prompt immediately after logging in (or right away if he/she is already logged in). See [Consent missing errors](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#consent-missing-errors). For linksk to sample code that shows error-handling in SSO, see the first paragraph of [errors-on-the-server-side-from-azure-active-directory](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#errors-on-the-server-side-from-azure-active-directory). I also recommend that you read that entire Troubleshooting article.

**Comment by redcirkle** [comment]
Awesome, we'll take a look at these articles. Thanks so much!

**Comment by qc-gordon** [comment]
This is the first hit on Google for this problem so I'll post an explanation here.

The person trying to grant admin consent would normally need [Application Administrator](https://docs.microsoft.com/en-gb/azure/active-directory/users-groups-roles/directory-assign-admin-roles#application-administrator) permissions. In this case, the permission involves the Graph API which is intentionally not allowed for this role.

> This means that a malicious user cannot easily elevate their permissions, for example by creating and consenting to an app that can write to the entire directory and through that app's permissions elevate themselves to become a global admin.

It looks like the [least privileged permission](https://docs.microsoft.com/en-gb/azure/active-directory/users-groups-roles/roles-delegate-by-task#enterprise-applications) needed to grant access to the Graph API is [Privileged Role Administrator](https://docs.microsoft.com/en-gb/azure/active-directory/users-groups-roles/directory-assign-admin-roles#privileged-role-administrator) but this also gives them control over role assignments including Global Admin so the recommendation is to give it to as few people as possible.
