### ISSUE TITLE
silently get an access token.

### ISSUE THREAD

**Issue by sandeepsa** [OfficeDev/Office-Add-in-ASPNET-SSO#40]
I am try to implement SSO with Outlook addin, solution works fine for Outlook web addin, and for Windows Outlook, SSO fails with error message platform not supported, and shows fallback authentication popup. I am trying to capture access token silently by passing authoption allowSignInPrompt: false. But it fails to get authenticated silently and shows popup. Please let me know what I am missing here. 
[allowsigninprompt](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.authoptions?view=excel-js-preview#allowsigninprompt)

EXCEPTION: {"name":"API Not Supported","message":"API is not supported in this platform.","code":13012}

**Comment by jargil** [comment]
@sandeepsa - what version of Outlook Desktop are you using?

**Comment by sandeepsa** [comment]
I have tested with: Version 1911(Build 12228.20364) and Version 1902(Build 11328.20480), on both same error message, API Not Supported. and fails to authenticate silently.

**Comment by jargil** [comment]
@sandeepsa - version 1902 is not supported, SSO is currently only on preview on monthly builds. Version 1911 does not support the latest revision of the API. As far as Monthly builds, to try SSO please join Office Insiders, you should then get either 1911 (16.0.12325.20172) if you choose Monthly or 16.0.12410.20000 if you choose Insider, builds may change depending when you join.

Let me know once you get a newer build if things start working for you.

**Comment by mikewalker74** [comment]
The question this then raises is the desired user flow and how to manage users with older office clients and gathering capabilities as sso is critical for a great consistent service. Can you suggest a pattern that you would expect to work for both scenarios and how to detect and be best practice please.

**Comment by jargil** [comment]
@mikewalker74 - our SSO samples provide a fallback using Dialog API that you can use as guidance:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet

**Comment by jargil** [comment]
Closing as there's been no more follow ups. Let us know if you're still having problems and we can reactivate.
