### ISSUE TITLE
Authorization has been denied for this request

### ISSUE THREAD

**Issue by Mike-tech** [OfficeDev/Office-Add-in-ASPNET-SSO#42]
Hello there

I have configured the ASPNET SSO application for this office add-in, and followed the configuration setup documented here:
[https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet)

I got this working on a non domain machine without any issue. I had the same setup on a client's domain machine and every time I start the Visual Studio application the getData call (/api/values) just returns Authorization has been denied for this request. 

I have configured the client id and secret and I have delegate permissions for Files.Read.All and profile. It's not even Files controller. 

Any suggestion where this may be failing or could this be a restriction of GPO? Any help will be appreciated. 

Thanks

**Comment by Rick-Kirkham** [comment]
Please clarify what you mean by a "domain machine" and a "non-domain machine". Thanks.

**Comment by Mike-tech** [comment]
Sorry i meant not working on machine joined to AD domain, which has GPO, etc. And the non domain machine is just a workgroup machine.

**Comment by Rick-Kirkham** [comment]
See if you can use the Fiddler tool to sniff the call to /api/values. See if the raw response has further information.

**Comment by Mike-tech** [comment]
I'm using a really locked down device and fiddler is blocked by the firewall. So pretty much flying blind. However I found the culprit. It was the api address port in the resource tag in Office-Add-in-ASPNET-SSO.xml. Not sure why, on my working solution I notice that this was using a different port number - so I changed it to api://localhost:44398/<my guid> and after that I no longer get error message described above.

But my next issue is repeated login prompt: https://localhost:4435/azureadauth/login. The login prompt for credentials and when I click on my username, it says Trying to log you in..., then goes back to Pick an account username. It just keep asking me for sign without visible error. Tried this on another user's machine and its the same. I'm working with the network team and they tried different policy without any luck. Any suggestions to what might be causing this or where to look - policy settings in Azure?

**Comment by Rick-Kirkham** [comment]
Sorry, but I've never seen that before. If it was happening to me, I'd use Fiddler to see what the response to the original login is and see if there are any clues to why it redirects back to login. But apparently you can't use Fiddler. 

Since you seem to be past the original problem, I'm going to close this.
