### ISSUE TITLE
Missing resid in manifest

### ISSUE THREAD

**Issue by elegault** [OfficeDev/Office-Add-in-ASPNET-SSO#44]
The add-in manifest (Complete/Office-Add-in-ASPNET-SSO/Office-Add-in-ASPNET-SSOManifest/Office-Add-in-ASPNET-SSO.xml) will fail to upload/validate because there is no Contoso.DesktopFunctionFile.Url resid value in the Resources element for the declared FunctionFile elements.

**Comment by Rick-Kirkham** [comment]
The FunctionFile elments shouldn't be in there.

**Comment by Rick-Kirkham** [comment]
I have fixed the manifest. Please see if it works now.

**Comment by elegault** [comment]
@Rick-Kirkham Yes, it does work
