### ISSUE TITLE
Cannot use WebApplicationInfo in manifest for Outlook

### ISSUE THREAD

**Issue by tnsholding** [OfficeDev/Office-Add-in-ASPNET-SSO#6]
I followed the guide and code for making SSO work in PowerPoint add-in. Everything works fine. 

Now I'm trying to get SSO to work in an Outlook add-in, but can't get the manifest right. 
Tried several different options (including nested VersionOverrides1_0 and VersionOverrides1_1 sections) but cannot get Outlook to accept WebApplicationInfo element. Any idea what I am doing wrong? - how should the manifest file look for SSO to work in Outlook?
I'm running Outlook desktop version 1708.

**Comment by Rick-Kirkham** [comment]
Have you tried this from the Overview article: 

"For Office hosts other than Outlook, add the markup to the end of the <VersionOverrides ... xsi:type="VersionOverridesV1_0"> section. For Outlook, add the markup to the end of the <VersionOverrides ... xsi:type="VersionOverridesV1_1"> section."

**Comment by tnsholding** [comment]
Yes. But maybe my formatting of the manifest is wrong. If I only have a VersionOverridesV1_1 section like this:
`  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
...
<WebApplicationInfo>
`

then I get an error:

> The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'VersionOverrides'

If I try to nest VersionsOverridesV1_1 inside a VersionOverridesV1_0 like this:
```
<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
...
<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
  
       <WebApplicationInfo>

```
I get the following error:

> A child node of the VersionOverrides node named WebApplicationInfo is invalid


Complete example of the last version of manifest attached (renamed from .xml to .txt to support upload):
[outlook-manifest.txt](https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO/files/1241350/outlook-manifest.txt)

**Comment by Rick-Kirkham** [comment]
"nest VersionsOverridesV1_1 inside a VersionOverridesV1_0" is exactly what you should do. I think you've got the manifest correct now.
It looks like your version of VS does not support the new markup. You'll have to do the workaround described in step 6 in the "Configure the add-in" section of this article: [create-sso-office-add-ins-aspnet](https://dev.office.com/docs/add-ins/develop/create-sso-office-add-ins-aspnet)

**Comment by tnsholding** [comment]
It seems I can get Outlook to accept the manifest when using debug from Visual Studio 2017 (with your suggested workaround to bypass the manifest warning). 
The same manifest fails if manually trying to sideload through the Outlook UI (Store -> add from file)?

But now I get an error: 13000 - api not supported. I got the same error in PowerPoint untill i upgraded to version 1708. I'm now on version 1709, but Outlook still complains that API not supported (Office.context.auth.getAccessTokenAsync). 
Do you know what version I need to have in order to get the 'getAccessTokenAsync' working in Outlook?

**Comment by Rick-Kirkham** [comment]
What user are you logging in as? Note this from the overview article about SSO: 
"Also, for Outlook, SSO only works if the Outlook account matches the Office user account listed in File > Office account."

**Comment by tnsholding** [comment]
I'm using the same account as listed under File -> Office account. So this should not be the issue.

**Comment by Rick-Kirkham** [comment]
@tnsholding 
Just an update, but not a solution yet. It looks like VS works a little differently when you debug an Outlook add-in from how it works with a Word/Excel/PowerPoint add-in. With Outlook, it uploads the manifest directly to Exchange instead of using the copy of it in `...\bin\Debug...`, so the workaround I pointed you to will not have any effect with an Outlook add-in. I think you are probably just going to have to wait until there's an update to VS 2017 Preview that recognizes the new markup. If the developers come up with a workaround before then, I'll pass it on here.

**Comment by Rick-Kirkham** [comment]
The developers tell me that they made a change on the server side, so this should work now. However:
1. You will probably still have to turn off the Build of the manifest project because VS still won't recognize the new markup.
2. Your `<Resource>` is `api://38346d83-d3d6-411d-9429-62e5caf401d3`. The domain should be a part of this. See step 9 of the Register section of https://dev.office.com/docs/add-ins/develop/create-sso-office-add-ins-aspnet and step 4 of the Configure section.

**Comment by manufz** [comment]
In my case Outlook does accept the manifest file when I add it to my account via OWA. However, when I try the `getAccessTokenAsync` I get the error 5013 (invalid API arguments)

The snippet of the manifest looks as follows:
```xml
<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
    ...
    <WebApplicationInfo>
      <Id>{App-ID}</Id>
      <Resource>api://myDomain.com/Home.html/{App-ID}<Resource>
      <Scopes>
        <Scope>openid</Scope>
        <Scope>offline_access</Scope>
        <Scope>files.read.all</Scope>
      </Scopes>
    </WebApplicationInfo>
</VersionOverrides>
```

I am not sure if my `Application ID URI` (in `<Resource>`) is in the right format?

**Comment by Rick-Kirkham** [comment]
Please clarify where/when you are seeing the 5013? For example, is it in the console? In Fiddler? Also, please show us call to getAccessTokenAsync, so we can see what arguments are being passed to it. Finally, is this really the same issue as originally raised? If not, it will help future devs who encounter this, if you create a new issue.

**Comment by manufz** [comment]
The error is thrown by getAccessTokenAsync. But it doesn't even call a Microsoft endpoint. Is this because of my Office version (1705)? Unfortunately I can't update yet to a newer version.

The full error is:
```
Code: 5013
Message: Invalid input arguments.
Name: API Call Failed
```

Edit: Opened new issue #12
