### ISSUE TITLE
getAccessTokenAsync returns error code 13000

### ISSUE THREAD

**Issue by imaksikkar** [OfficeDev/Office-Add-in-ASPNET-SSO#7]
Working off of the Complete version of this sample as of commit 8f90156, the call to `getAccessTokenAsync` returns the following error: 

![image](https://user-images.githubusercontent.com/3792784/29899912-11be0156-8da3-11e7-88c6-645fdcea2ced.png)

I'm using Office 2016 build 8431. I think this is update 1708. 
On Visual Studio 2017 version 15.3.3

I followed the application registration steps completely and successfully consented using the same admin account in my Office 365 tenancy. I am logged in as that same admin in PowerPoint (and no other users are logged in) when I click "Get My Files from OneDrive".

Fiddler isn't recording much that seems useful after I click the button but here's a screenshot.

![image](https://user-images.githubusercontent.com/3792784/29900130-8d1b5956-8da4-11e7-8da6-d524dc53a773.png)

I did use the elements `<WebApplicationId>`, `<WebApplicationResource>` and `<WebApplicationScopes>` in the add-in's manifest instead of doing the workaround for `<WebApplicationInfo>`, in case that's relevant.

**Comment by imaksikkar** [comment]
Just updated to use the workaround to put the `<WebApplicationInfo>` element in the add-in manifest and the error I'm getting on `getAccessTokenAsync` changed to this:

![image](https://user-images.githubusercontent.com/3792784/29900393-7010cc90-8da6-11e7-8cb1-e4d85808ee2f.png)

And the fiddler trace now shows this:

![image](https://user-images.githubusercontent.com/3792784/29900428-a8173ab6-8da6-11e7-919d-017d8cfd7a5b.png)

At this point, this issue seems like a potential duplicate of #5.

**Comment by imaksikkar** [comment]
The body of the request that 400s to **login.windows.net/common/oauth2/token** looks like this:

grant_type=refresh_token
&refresh_token=[TOKEN_HERE]
&redirect_uri=urn:ietf:wg:oauth:2.0:oob
&client_id=d3590ed6-52b3-4102-aeff-aad2292ab01c
&resource=api://localhost:44356/[MY_APP_ID_HERE]

and the response gives error_code 70011 with the error_description "AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope profile is not valid."

In the manifest of my app, I only see three scopes:

`"requiredResourceAccess": [
        {
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "df85f4d6-205c-4ac5-a5ea-6bf408dba283",
                    "type": "Scope"
                },
                {
                    "id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
                    "type": "Scope"
                },
                {
                    "id": "37f7f235-527c-4136-accd-4a02d197296e",
                    "type": "Scope"
                }
            ]
        }
    ]
`

Based on what I have set up in the Application Registration Portal, those should be for `Files.Read.All`, `offline_access` and `openid`. I used to have the scope for `User.Read` as well and removed it based on the advice in issue #5, but this didn't seem to change the error. It seems to be complaining about the profile scope, which as far as I can tell isn't something my application should be requesting. Any input here?

**Comment by Rick-Kirkham** [comment]
I notice that resource is localhost:4435**6**. I think it is 4435**5** in the sample. It should be OK to change it, but you need to be sure you are consistent in changing it every where and also replacing 44355 with 44356 when you follow the steps of: [Create SSO Office Add-ins ASP.NET](https://dev.office.com/docs/add-ins/develop/create-sso-office-add-ins-aspnet).

UPDATE: This might have been our fault. There were actually two places in the "Complete" version of the sample where we had 44356. One place was in server side code that wasn't running if you are getting 13007, so that wasn't the cause. (And the parameter in question has no effect in the on-behalf-of flow anyway.) But the other place was one of the .csproj files. I wonder if that could be the source of your issue. I've uploaded a fixed version. But you shouldn't have to download again. Instead, could you close Visual Studio, then open the following file in a text editor: https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO/blob/master/Complete/Office-Add-in-ASPNET-SSO-WebAPI/Office-Add-in-ASPNET-SSO-WebAPI.csproj. Search for the 44356 and replace it with 44355. Save the file and reopen the project in VS. Test to see if that fixes anything.

**Comment by imaksikkar** [comment]
Changing it only in the .csproj file didn't seem like enough, it still showed port 44356 in the Properties window and IIS Express also showed the site as running on 44356, like so:

![image](https://user-images.githubusercontent.com/3792784/29948977-96ee3d3c-8e66-11e7-8ceb-e2626f584429.png)

Changing the 44356 to 44355 in the .csproj.user file as well did the trick though and the site is now starting up on port 44355. This appears to have broken the app though, the add-in gives the following error and http://localhost:44355 can't be reached. I'm not sure how to go farther down this path since the add-in can't run in this state.

![image](https://user-images.githubusercontent.com/3792784/29949001-ca966d62-8e66-11e7-8968-cbb801457435.png)

I noticed one thing that might be useful. I started from scratch (to rule out user error) by registering a brand new app for the sample. When I clicked to set up the Delegated Permissions, `User.Read` was already checked by default and this time I unchecked it so that in the end only `Files.Read.All`, `openid` and `offline_access` were checked. Despite only having three things checked, when I went to grant admin consent to the add-in I was still prompted with the same four bullets I'd seen when I left `User.Read` checked the first time I tried this. One of those four bullets mentions reading a user's profile. I thought this may be related to the error I'm seeing since it seems to complain about the profile scope.

![image](https://user-images.githubusercontent.com/3792784/29949142-8f1321c6-8e67-11e7-9ac4-0f82ad1c54c5.png)

**Comment by Rick-Kirkham** [comment]
The .csproj.user  is not part of the repo itself. It gets recreated the first time you open the solution after cloning/downloading. So it makes sense that you would have to change it there too. In retrospect, I should have suggested that you just download the new version and start with that. 

Regarding the new issue: After you've pressed F5, can you open the home page in a browser if you enter the full URL? It should be: http**s**://localhost:44355/home/index (Note the "s" in the protocol.)

The Delegated Permissions is the permissions of the add-in to MS Graph. You're not getting to the point where that code even runs, so I don't think any puzzles with that are going to explain your current symptoms. The references to "profile" in the error you were seeing are misleading. (I would speculate that one of the other permissions, like maybe Files.Read.All itself requires User.Read, so you are prompted to grand User.Read too.)

**Comment by cognologixguru** [comment]
Hi Rick,
I tried your solution for **Error Code 13000** but my application is showing same error and I am unable to call Office SingleSignOn API.

**Comment by imaksikkar** [comment]
That makes sense about the delegated permissions theory. Okay so I did end up downloading the new version after having issues doctoring up the new one. Everything there is running smoothly on port 44355 but I'm getting the exact same error (13007) and Fiddler looks the same as well. 

In case it's useful, here's the request to login.windows.net that 400s:

```
POST https://login.windows.net/common/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
client-request-id: [RANDOM_GUID]
return-client-request-id: false
x-client-OS: 10.0.14393
x-client-SKU: Win32
x-client-Ver: v1.0.-13.20
x-ms-PKeyAuth: 1.0
Host: login.windows.net
Content-Length: 1016
Cache-Control: no-cache
Cookie: x-ms-gateway-slice=008; stsservicecookie=ests

grant_type=refresh_token&refresh_token=AQA...&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=d3590ed6-52b3-4102-aeff-aad2292ab01c&resource=api://localhost:44355/[MY_APPLICATION_ID]
```

and here's the response:

```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
client-request-id: d285...
x-ms-request-id: 585b...
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: esctx=[VALUE]; domain=.login.windows.net; path=/; secure; HttpOnly
Set-Cookie: x-ms-gateway-slice=008; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Date: Fri, 01 Sep 2017 16:49:11 GMT
Content-Length: 461

{"error":"invalid_scope","error_description":"AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope profile is not valid.\r\nTrace ID: 585b...\r\nCorrelation ID: d285...\r\nTimestamp: 2017-09-01 16:49:10Z","error_codes":[70011],"timestamp":"2017-09-01 16:49:10Z","trace_id":"585b...","correlation_id":"d285..."}
```

Is there any other info I can share that could help resolve this?

**Comment by Rick-Kirkham** [comment]
There's an internal email thread about 13007 going on today. There is a report, from someone working on an Outlook add-in, that you can fix the error by going back to the app registration and adding "profile" to the **Microsoft Graph Permissions**. Then redo the admin consent. Please give this a try and let us know if it has any effect.

**Comment by prashantharshi** [comment]
Solved the issue when added "profile" to the oauth scope

**Comment by manufz** [comment]
Adding "profile" to the delegated permissions worked for me as well! Thanks. :)

**Comment by imaksikkar** [comment]
This fixed this issue for me as well, thanks!
