### ISSUE TITLE
successfully getting add-in token , but call doesnt reach to ValueController.CS

### ISSUE THREAD

**Issue by prashantharshi** [OfficeDev/Office-Add-in-ASPNET-SSO#9]
Hi i successfully got the add-in token from the getAccessTokenAsync call but in the later ajax calls to api/values , the call should go the corresponding controller ie valuescontroller.cs but the debugger doesnt hit there and in the ajax response result i get to see , Message":"Authorization has been denied for this request. Also i see several js runtime exceptions  which i have attached in screenshot. 
Can you help me out what i am missing 
![sso](https://user-images.githubusercontent.com/8679965/30115901-b1875322-9339-11e7-9110-9d85b654e2a5.PNG)

**Comment by Rick-Kirkham** [comment]
Please use the [Fiddler tool](http://www.telerik.com/fiddler) to capture the traffic when you press the button **Get My Files from OneDrive**. See if the Request and Response for the call to `api/values `contain any further information.

**Comment by TimMcMSFT** [comment]
Hi Prashant, have you ensured that the OWIN auth config is correct? Specifically, have you ensured that your application is the Audience and that your Tenant is a safe Issuer?

**Comment by Rick-Kirkham** [comment]
Haven't heard back from customer, so closing.

**Comment by prashantharshi** [comment]
Thanks rick :)
